### ISSUE TITLE
[bug]The released flink-siddhi_2.11-0.2.2-SNAPSHOT.jar has old code 

### ISSUE THREAD

**Issue by lovepoem** [haoch/flink-siddhi#71]
Recently , I use flink-siddhi in my project , but I find the code from jar did not match the source code here `https://github.com/haoch/flink-siddhi`

![image](https://user-images.githubusercontent.com/827112/103601856-87865e80-4f45-11eb-8208-81a7ab341783.png)  jars 

https://repo.clojars.org/com/github/haoch/flink-siddhi_2.11/0.2.2-SNAPSHOT/

eg.
`org.apache.flink.streaming.siddhi.utils.SiddhiExecutionPlanner.StreamPartition`

have no 

```java

private List<String> partitionWithList = new ArrayList();

        public List<String> getPartitonWithList() {
            return this.partitionWithList;
        }

```

code in jar , but the source code contains it 

Would you please release it again, thanks

**Comment by haoch** [comment]
Thanks for reporting the issue. It's updated now, please have a try again: https://repo.clojars.org/com/github/haoch/flink-siddhi_2.11/0.2.2-SNAPSHOT/flink-siddhi_2.11-0.2.2-20210106.071414-6.pom

**Comment by lovepoem** [comment]
![image](https://user-images.githubusercontent.com/827112/103743698-8df50300-5037-11eb-9f73-f4cbf8bb28bc.png)

https://github.com/haoch/flink-siddhi/blob/cf4b2b6935bc69be1b465e49431bb8485e4d670b/core/src/main/java/org/apache/flink/streaming/siddhi/utils/SiddhiExecutionPlanner.java#L293

It seems that the difference still exist

**Comment by lovepoem** [comment]
Now fixed , thank you
